ci: add support for django 3.2
django-cms/django-classy-tags pull request #61
Opened 2021-09-10 18:07 UTC by mariajgrimaldi

**Description**
This PR supports Django 3.2 in CI as the Open edX community effort to give Django 3.2 support to all its dependencies. [Here](https://github.com/edx/upgrades/issues/39)'s the issue if you're interested.

2021-09-10 18:09 UTC, mariajgrimaldi commented
Hi there @NarenderRajuB! 
I'm tagging you in this issue as you're the latest contributor to the repo! Can you help me move this forward?

2021-09-14 13:12 UTC, marksweb requested changes
Added a couple of minor requests to help the test suite going forwards.

2021-09-14 13:12 UTC, marksweb commented on tests/requirements/dj32_cms39.txt
> +django-cms>=3.9
I'd make this `django-cms>=3.9,<4` because we're working on version 4

2021-09-14 13:12 UTC, marksweb commented on tox.ini
>      py{35,36,37,38}-dj{22}
Could you please drop python 3.5 from here and add 3.9 to both django 2.2 and 3.x?

2021-09-14 19:19 UTC, mariajgrimaldi commented
Hey! @marksweb I followed your suggestions! Thank you

2021-09-14 19:26 UTC, marksweb approved these changes

2021-09-14 19:28 UTC, merged

2021-09-14 19:28 UTC, marksweb commented
@mariajgrimaldi fantastic, thank your for your contribution.

2021-09-14 20:44 UTC, mariajgrimaldi commented
Great! Thank you @marksweb 
I'm looking forward to the new release! :)

2021-09-14 21:09 UTC, marksweb commented
@mariajgrimaldi I can't actually do releases but I've raised with the team the fact that this needs a 3.2 compatible release following these changes 👍